FROM node:20-alpine

WORKDIR /app

# Copia pacotes para cache de dependências
COPY package*.json ./

RUN npm install

# Copia código fonte
COPY . .

EXPOSE 3000

# Executa o Next.js com binding em 0.0.0.0 para aceitar conexões vindas de fora do container
CMD ["npx", "next", "dev", "--hostname", "0.0.0.0", "-p", "3000"]
